services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole-dns:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_VERSION:-latest}
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # See https://docs.pi-hole.net/main/prerequisites/#ports
    ports:
      - ${PIHOLE_DNS_PORT:-53}:53/tcp
      - ${PIHOLE_DNS_PORT:-53}:53/udp
      - ${PIHOLE_DHCP_PORT:-67}:67/udp # Only required if you are using Pi-hole as your DHCP server
      - ${PIHOLE_UI_PORT:-80}:80/tcp
    # View all environment variables at
    # https://github.com/pi-hole/docker-pi-hole/?tab=readme-ov-file#optional-variables
    environment:
      TZ: ${TZ:-Etc/UTC}
      WEBPASSWORD: ${PIHOLE_PASSWORD:-changeme}
    volumes:
      - ${PIHOLE_CONFIG_DIR:-./data/etc-pihole}:/etc/pihole:z
      - ${PIHOLE_DNSMASQ_DIR:-./data/etc-dnsmasq.d}:/etc/dnsmasq.d:z
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: always
